# Generated by Django 5.1.2 on 2024-10-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.CharField(max_length=255),
        ),
    ]
